# To do: use a lighter image if available / necessary
image: node:4.6.0
pipelines:
  branches:
    master:
      - step:
          script:
          - echo "To do: run make here"
          - npm install -g aerobatic-cli
          - aero deploy
